# バージョンNO
# 1 -> 0001
# 2 -> 0010
# 3 -> 0011
# 4 -> 0100
version: "0100"

# 情報サイズ
# 4オクテット情報サイズ = 1
# ex.サイズが20バイトの場合は 5 -> 0101
size: "0101"

# 予備
reserve1: "0000"

# 電文順序番号
sequence_no: "00000000000011100101"

# 中継種別
# 0 -> 通常の中継
# 1 -> 着信官署端末番号による単純中継
relay_type: "0"

# 地震フラグ
# 0 -> 通常電文
# 1 -> 地震・津波電文
earthquake_flg: "0"

# 予備
reserve2: "0"

# テストフラグ
# 0 -> 通常電文
# 1 -> テスト電文
test_flg: "0"

# XMLフラグ
# 00 -> XML以外の電文
# 01 -> XMLで圧縮なし
# 10 -> XMLでgzip圧縮
# 11 -> XMLでzip圧縮
xml_flg: "01"

# データ機密度
# (未使用)
degree_of_secrecy: "00"

# データ属性
# 0000 -> 未使用
# 0001 -> 1バイト系
# 0010 -> 漢字(シフトJIS)
# 0011 -> 漢字(JIS)
# 0100 -> 予備
# 0101 -> バイナリ
data_attribute: "0101"

# 気象庁内配信情報
distribute_info: "0000"

# データ種別
# 上位4bitが大分類,下位4bitが小分類
data_type: "00000000"

# 予備
reserve3: "00000000"

# BIF再送フラグ
# 0 -> 再送電文以外
# 1 -> 再送電文
bif_resend_flg: "0"

# BIFデータ属性
# 000 -> 1バイト系
# 001 -> 1バイト系
# 010 -> 漢字(シフトJIS)
# 011 -> バイナリ
bif_data_attribute: "011"

# BIFデータ種別
# 0000 運用報
# 0001 ツナミ報
# 0010 ケンソク報
# 0011 シンゲン報
# 0100 ヒジョウ報
# 0101 ジシン報
# 0110 一般気象報
# 0111 CDF報
# 1000 SGT報
# 1001 DRE報
# 1010 メール報
# 1011 バッチ系バイナリ報
# 1100 GTSバイナリ報
# 1101 国内バイナリ報
# 1110 降水強度指数データ
# 1111 その他
bif_data_type: "0000"

# A/N桁数
# バイナリ電文のBCHの次の文字から電文本文直前までのA/N桁数
an_length: "00000000"

# QCチェックサム
checksum: "1011011110000010"

# 発信官署番号 大分類
send_agency_major: "00"

# 発信官署番号 該当システムビット
send_agency_bit: "00000000000000"

# 発信官署番号 各システムの管理する端末の番号
send_agency_termno: "0000000000000000"

# 着信官署番号 大分類
recv_agency_major: "00"

# 着信官署番号 該当システムビット
recv_agency_bit: "00000000000000"

# 着信官署番号 各システムの管理する端末の番号
recv_agency_termno: "0000000000000000"

