# 接続先サーバのIPアドレスまたはホスト名
# host: "203.138.187.88" # prototype A
# host: "203.138.187.89" # prototype B
host: "localhost" # local

# 接続先サーバのポート番号
port: 30000

# ヘルスチェックの再試行インターバル
keepalive_interval: 30

# サーバ接続時の再試行インターバル
open_interval: 10

# UnixDomainSocketファイル
unix_socket: "/tmp/jmaclient.sock"

# ヘッダ付与モード
# 0 -> ヘッダ付与なし
# 1 -> JMAヘッダを付与
# 2 -> BCH,TCHヘッダを付与
data_mode: 2

